---
title: "Informedb Analysis"
author: "Liam Whitenack"
date: "r Sys.Date()"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(infer))
suppressPackageStartupMessages(library(modelr))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(rlang))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(shiny))
suppressPackageStartupMessages(library(shinythemes))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(datasets))
suppressPackageStartupMessages(library(anytime))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(scales))
Jira_reduced <- read_csv("Jira_reduced.csv")
```

This R Markdown document is made interactive using Shiny. Unlike the more traditional workflow of creating static reports, you can now create documents that allow your readers to change the assumptions underlying your analysis and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

```{r reference_chunk, eval=FALSE, include=FALSE}
# the ui should contain the input and the display code
ui <- fluidPage(
  
)
# the server should contain the code for whatever uses the input
server <- function(input, output) {
  
}

 #this code doesn't need to be edited
shinyApp(ui = ui, server = server)
```


## Inputs and Outputs
```{r histogram, echo=FALSE}
# create ui to display
ui <- fluidPage(
  
  #make spearate panels so that the project can be viewed side by side
  
  sidebarLayout(
    
    # start a panel with interactive buttons
      
    sidebarPanel(
      # create a dropdown list with the names of the columns that we're looking to examine
      
      selectInput(
        inputId = "action",
        label = "Parameters",
        choices=c("date_created", "date_updated", "date_resolved"),
        selected = "date_created"
      ),
      
      # create a slider that chooses the day the histogram looks at
      
      sliderInput(
        inputId = "start_date_resolved", 
        label = "Choose a start date", 
        value = as.Date(max(Jira_reduced$date_created)-365), 
        min = as.Date(min(Jira_reduced$date_created)), 
        max = as.Date(max(Jira_reduced$date_created)-182)
      ),
      
      # create a slider that chooses the amount of bins on the histogram
      
      sliderInput(inputId = "bins", label = "Choose the number of bins", value = 12, min = 6, max = 60, step = 6),
    ),
  
  #start a main panel to display the graphs we want
  
  mainPanel(
    
    #plot the histogram made in the server function
    
    plotOutput("histogram")
  )
  )
)

#create the server function responsible for reacting to the different sliders

server <- function(input, output) {
  
  # create my histogram
  output$histogram <- renderPlot({
    # use ggplot to make a plot
    ggplot()+
      geom_histogram(
      aes(
          #use the user-input parameter chosen as the x value
        x = (as.POSIXct(array(c(data.matrix((Jira_reduced[,input$action]))))*24*60*60, origin="1970-01-01")),
          # color by priority
        fill = Jira_reduced$Priority
      ), #use the user input for bins
      bins = input$bins
  )+ 
      # the xlim is determined by the user, using input$start_date_resolved, 
      # so that they can determine how much time they want to look at. 
      # The xmax is the max of the data being looked at.
  xlim(as.POSIXct(input$start_date_resolved),
max((as.POSIXct(array(c(data.matrix((Jira_reduced[,input$action]))))*24*60*60, origin="1970-01-01")))) +
      #rename the labels of the graph
  xlab(input$action)+
  ylab("Count") +
  labs(fill = "Priority", title = "Defect Trends")
  })
}

# print all to the screen

shinyApp(ui = ui, server = server)
```
```{r scatterplot, echo=FALSE}
# the ui should contain the input and the display code
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      
      # create three lists of column names to be used as variables
      
      selectInput(
        inputId = "xvar",
        label = "X Variable:",
        choices=colnames(Jira_reduced)[6:12],
        selected = "date_created"
      ),
      
      selectInput(
        inputId = "yvar",
        label = "Y Variable:",
        choices=colnames(Jira_reduced)[6:12],
        selected = "time_spent"
      ),
      
      selectInput(
        inputId = "color",
        label = "Color By:",
        choices=colnames(Jira_reduced)[1:5],
        selected = "Priority"
      ),
    ),
    
    # plot our graph
    
    mainPanel(
      plotOutput("scatterplot")
    )
  )
)
# the server should contain the code for whatever uses the input
server <- function(input, output) {
  
  # create the scatterplot
  
  output$scatterplot <- renderPlot({
    ggplot()+
      geom_point(
        aes(
          
          # the three different selectInput() functions should determine the axis variables
          
          x = array(c(data.matrix((Jira_reduced[,input$xvar])))),
          y = array(c(data.matrix((Jira_reduced[,input$yvar])))),
          color = array(c(as.matrix(Jira_reduced[,input$color]))),
          na.rm = TRUE
        ), 
        
      ) +
      xlim(
        min(array(c(data.matrix((Jira_reduced[,input$xvar])))), na.rm = TRUE),
        max(array(c(data.matrix((Jira_reduced[,input$xvar])))), na.rm = TRUE)
      ) +
      ylim(
        min(array(c(data.matrix((Jira_reduced[,input$yvar])))), na.rm = TRUE),
        max(array(c(data.matrix((Jira_reduced[,input$yvar])))), na.rm = TRUE)
      ) +
      xlab(input$xvar)+
      ylab(input$yvar) +
      labs(color = input$color, title = "Defect Scatterplot") +
      geom_smooth(
        aes(
          x = array(c(data.matrix((Jira_reduced[,input$xvar])))),
          y = array(c(data.matrix((Jira_reduced[,input$yvar]))))
        )
      )
  })
}

 #this code doesn't need to be edited
shinyApp(ui = ui, server = server)
```
```{r time_spent_hist, echo=FALSE}
# the ui should contain the input and the display code
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      selectInput(
        inputId = "time",
        label = "Choose your Column:",
        choices=c("time_spent", "repair_time"),
        selected = "date_created"
      ),
      sliderInput(
        inputId = "max_time", 
        label = "Choose a range:", 
        value = (max(Jira_reduced$time_spent)-500), 
        min = 31, 
        max = (max(Jira_reduced$time_spent))
      ),
      sliderInput(
        inputId = "breaks", 
        label = "Choose the number of bins:", 
        value = 10, 
        min = 5, 
        max = 20
        ),
    ),
    mainPanel(
      plotOutput("histy")
    )
  )
)
# the server should contain the code for whatever uses the input
server <- function(input, output) {
  output$histy <- renderPlot({
  ggplot()+
    geom_histogram(aes(x = array(c(data.matrix(Jira_reduced[,input$time]))), fill = Jira_reduced$Priority), bins=input$breaks) +
                     xlim(0, as.numeric(input$max_time)) +
      xlab(input$time)
  })
}

 #this code doesn't need to be edited
shinyApp(ui = ui, server = server)
```

