---
title: "Assignment 11"
author: "Liam Whitenack"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output: flexdashboard::flex_dashboard
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  fig.width = 5,
  fig.asp = 0.618,
  out.width = "70%",
  dpi = 120,
  fig.align = "center",
  cache = FALSE
)
library(tidyverse)
library(plotly)
library(crosstalk)
pokemon <- read_csv("pokemon.csv")
shared_pokemon <- SharedData$new(pokemon)
```


Column
-------------------------------------
### Pokemon Boxplot
 
```{r, echo = FALSE}
box <- shared_pokemon %>%
  ggplot() +
  geom_boxplot(aes(x = reorder(`Type 1`, Total, FUN=median), y = Total, fill = `Type 1`)) +
  labs(x = "Pokemon Type") + 
  theme(axis.text.x = element_text(angle = 45))

ggplotly(box)
```
 
Column
-------------------------------------
### Pokemon Scatterplot
```{r, echo = FALSE}
p <- shared_pokemon %>%
  ggplot() +
   geom_point(
     mapping = aes(x = Defense, y = Attack, color = `Type 1`)
   )

ggplotly(p)
```

SidebarName {.sidebar}
----------------------
```{r, echo = FALSE}
filter_select("Assignee", "Assignee", shared_pokemon, ~`Type 1`)
```
